name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build and Export Static Files
      run: |
        npm run build
        npm run export

    - name: Deploy to Azure Web App (via Publish Profile)
      uses: azure/webapps-deploy@v2
      with:
        app-name: UserCenter-Demo  # 注意：这里要与你 Azure Web App 名称完全一致
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./out
